### ISSUE TITLE
why not use tensorflow keras instead

### ISSUE THREAD

**Issue by lomessa** [google/trax#1497] opened 2021-02-24 10:01 UTC
### Description

...

### Environment information

```
OS: <your answer here>

$ pip freeze | grep trax
# your output here

$ pip freeze | grep tensor
# your output here

$ pip freeze | grep jax
# your output here

$ python -V
# your output here
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
...
```

```
# Error logs:
...
```

**Comment by pkozakowski** [comment] 2021-02-24 13:09
You don't have to choose either TRAX or Keras - you can use your TRAX models in Keras using this wrapper: https://github.com/google/trax/blob/master/trax/trax2keras.py.

**Comment by afrozenator** [comment] 2021-05-22 18:25
+1 to @pkozakowski 's comment. Closing as this is intended behaviour.

**Closed by afrozenator** 2021-05-22 18:25 UTC
